# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [46]:
# Print out dimension (number of axes)
print(f"Number of dimensions (axes): {A.ndim}")
print()

# Shape
print(f"Shape: {A.shape}")
print()

# Size
print(f"Size (total elements): {A.size}")
print()

# Type
print(f"Data type: {type(A)}")
print()

Number of dimensions (axes): 2

Shape: (3, 5)

Size (total elements): 15

Data type: <class 'numpy.ndarray'>



### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [14]:
# Elementwise subtraction
D = B - C
print(D)
print()

# Elementwise multiplication
E = B * C
print(E)
print()

# Matrix multiplication
F = B @ C
print(F)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [38]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
# Exponentiate number
C = np.exp(B)
print(f"Exponentiate number: \n{C}\n")

# Calculate min value in whole matrix
D = B.min()
print(f"Calculate min value in whole matrix: \n{D}\n")

# Calculate min value in each row
E = B.min(axis=1)
print(f"Calculate min Value in each row: \n{E}\n")

# Calculate min value in each column
F = B.min(axis=0)
print(f"Calculate min value in each column: \n{F}\n")

# Index value for the minimum value in the whole matrix
G = np.argmin(B)
print(f"Index value for the minimum value in the whole matrix: \n{G}\n")

# Index value for the minimum value in each row
H = np.argmin(B, axis=1)
print(f"Index value for the minimum value in each row: \n{H}\n")

# Calculate the sum for all elements
J = B.sum()
print(f"Calculate the sum for all elements: \n{J}\n")

# Calculate the mean for each column
K = np.mean(B,axis=0)
print(f"Calculate the mean for each column: \n{K}\n")

# Calculate the median for each column
L = np.median(B, axis=0)
print(f"Calculate the median for each column: \n{L}\n")

Exponentiate number: 
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Calculate min value in whole matrix: 
1

Calculate min Value in each row: 
[1 4 7]

Calculate min value in each column: 
[1 2 3]

Index value for the minimum value in the whole matrix: 
0

Index value for the minimum value in each row: 
[0 0 0]

Calculate the sum for all elements: 
45

Calculate the mean for each column: 
[4. 5. 6.]

Calculate the median for each column: 
[4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [44]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
A[1]

array([ 2,  7, 12])

**Answer:**

When you provide fewer indices than are axes while slicing an array, entire rows or columns are returned depending on the axis you specified. In this example A[1], it returned the second row of the matrix. To return a column you have to specify the column index while slicing. You need to use a colon to indicate all rows, and then specify the column. For example A[:,1].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [55]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [56]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [59]:
# Iterate throught the array elementwise by using .flat attribute
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [60]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### a = np.arange()
This creates a variable a. The function np.arange() is analogous to Python's range(), but it returns an array instead of a list. np.arange() is a NumPy function that creates an array of evenly spaced values within a given interval. In this case, it generates values starting from 0 up to, but not including, 30 (so from 0 to 29). The step value is defaulted to 1 unless specified otherwise.
#### b = a.reshape(2, 3, -1)
This creates a variable b. The function reshape() is used to change the shape of the array a into a 3-dimensional array. The first argument 2 means that the new array will have 2 blocks. The second argument 3 means that each block will have 3 rows. The third argument -1 automatically calculates the appropriate number of columns per row, based on the total number of elements. Here, since a has 30 elements, and we are reshaping it into 2 blocks and 3 rows, the -1 computes to 5 columns (since 30 ÷ (2 * 3) = 5).
#### print(a) print() print(b)
print(a) prints variable a. print() creats a empty row, and print(b) prints variable b.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)